version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gym_postgres
    restart: always
    environment:
      POSTGRES_DB: gymdb
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gympass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: gym_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
